version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - 3000:3000